language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=Django==1.8

install:
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.6" ]]; then pip install importlib unittest2 "markdown<=2.4"; fi
  - pip install $DJANGO flake8 python-coveralls
  - pip install -e .
  - pip install "file://`pwd`#egg=djedi-cms[tests]"

script:
  - make flake8
  - coverage run --source djedi runtests.py
  - coverage report

after_success:
  - coveralls
