language: python
sudo: false
env:
  - TOXENV=py26-django14
  - TOXENV=py27-django14
  - TOXENV=py26-django15
  - TOXENV=py27-django15
  - TOXENV=py26-django16
  - TOXENV=py27-django16
  - TOXENV=py33-django16
  - TOXENV=py34-django16
  - TOXENV=py27-django17
  - TOXENV=py33-django17
  - TOXENV=py34-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django18
  - TOXENV=py34-django18
  - TOXENV=flake8
  - TOXENV=coverage


install:
  - pip install tox

script:
  - tox

deploy:
  provider: script
  script: pip install --quiet python-coveralls && coveralls
